version: '3.5'

services:
  sastamedicine-postgres:
    container_name: sastamedicine-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - ./.data/postgres:/data/postgres
    ports:
      - "5432:5432"

  sastamedicine-backend:
    container_name: sastamedicine-backend
    image: sastamedicine-backend
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      target: sastamedicine-backend
    ports:
      - "5000:5000"
    volumes:
      - ./apps/backend/src:/opt/app/backend/src
      - ./apps/backend/prisma:/opt/app/backend/prisma
    environment:
      POSTGRES_HOST: sastamedicine-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: sastamedicinedb
    depends_on:
      - sastamedicine-postgres 

volumes:
  postgres:
  sastamedicine-backend:
  # pgadmin:
  # backend_node_modules: