version: '3.5'

services:
  ##########
  # Database
  ##########
  sastamedicine-postgres:
    container_name: sastamedicine-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - ./.data/postgres:/data/postgres
    ports:
      - "5432:5432"

  ##########
  # Backend
  ##########
  sastamedicine-backend:
    container_name: sastamedicine-backend
    image: sastamedicine-backend
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      target: sastamedicine-backend
    ports:
      - "5000:5000"
    volumes:
      - ./apps/backend/src:/opt/app/backend/src
      - ./apps/backend/prisma:/opt/app/backend/prisma
    environment:
      POSTGRES_HOST: sastamedicine-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: sastamedicinedb
      DATABASE_URL: postgresql://postgres:password@localhost:5432/sastamedicinedb?schema=public
    depends_on:
      - sastamedicine-postgres 

  ##########
  # Frontend
  ##########
  sastamedicine-frontend:
    container_name: sastamedicine-frontend
    image: sastamedicine-frontend
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      target: sastamedicine-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend/app:/opt/app/frontend/app

volumes:
  postgres:
  sastamedicine-backend:
  sastamedicine-frontend:
  # pgadmin: